export type BookingLocale = "es" | "en";

const STRINGS = {
  es: {
    metaTitle: "Reservar | Hostal Costabella",
    navBook: "Reservar",
    stepSearch: "Búsqueda",
    stepRooms: "Habitaciones",
    stepDetails: "Datos",
    stepPayment: "Pago",
    langEs: "ES",
    langEn: "EN",
    searchTitle: "Encuentra tu estancia",
    searchSubtitle:
      "Selecciona fechas y número de huéspedes. Mejor precio al reservar en la web oficial.",
    checkin: "Entrada",
    checkout: "Salida",
    adults: "Adultos",
    children: "Niños",
    searchCta: "Ver habitaciones disponibles",
    roomsTitle: "Habitaciones disponibles",
    roomsSubtitle: "Elige la opción que mejor encaje con tu viaje.",
    nights: "noches",
    night: "noche",
    perNight: "por noche",
    totalStay: "Total estancia",
    taxesNote: "Impuestos incluidos. Política de cancelación según tarifa.",
    selectRoom: "Seleccionar",
    modifySearch: "Modificar búsqueda",
    guestsSummary: "Huéspedes",
    adultsWord: "adultos",
    adultWord: "adulto",
    childrenWord: "niños",
    childWord: "niño",
    roomWord: "habitación",
    roomsWord: "habitaciones",
    availabilityOk: "Disponible",
    availabilityFew: "Últimas habitaciones",
    back: "Volver",
    backHome: "Inicio",
    detailsTitle: "Datos de la reserva",
    detailsSubtitle: "Completa la información del titular de la reserva.",
    fullName: "Nombre y apellidos",
    email: "Correo electrónico",
    phone: "Teléfono",
    country: "País / región",
    specialRequests: "Peticiones especiales (opcional)",
    specialPlaceholder: "Horario aproximado de llegada, preferencias de habitación…",
    continuePayment: "Continuar al pago",
    paymentTitle: "Pago seguro",
    paymentSubtitle: "Introduce los datos de tu tarjeta para completar la reserva.",
    summaryRoom: "Habitación",
    summaryGuest: "Titular",
    summaryStay: "Estancia",
    summaryTotal: "Importe a pagar",
    cardNumber: "Número de tarjeta",
    cardExpiry: "Caducidad",
    cardCvc: "CVC",
    payMethodCard: "Tarjeta de crédito o débito",
    payMethodBizum: "Bizum",
    payMethodTransfer: "Transferencia bancaria",
    payCta: "Pagar y confirmar reserva",
    payProcessing: "Procesando pago…",
    confirmTitle: "Reserva confirmada",
    confirmSubtitle:
      "Gracias. Hemos registrado tu reserva y te hemos enviado un correo con todos los detalles.",
    confirmLocator: "Localizador",
    confirmEmailNote: "Revisa tu bandeja de entrada y la carpeta de spam.",
    homeCta: "Volver al inicio",
    errorDates: "Las fechas no son válidas. La salida debe ser posterior a la entrada.",
    errorGuests: "Indica al menos un huésped.",
    errorRoom: "No hay habitaciones para el número de huéspedes indicado. Ajusta la búsqueda.",
    errorMissingRoom: "Selecciona una habitación para continuar.",
    roomNames: {
      "doble-matrimonial": "Habitación doble (cama matrimonial)",
      "doble-twin": "Habitación doble (camas individuales)",
      triple: "Habitación triple",
      "doble-mas-individual": "Habitación doble + cama individual",
      familiar: "Habitación familiar",
      individual: "Habitación individual",
    },
    roomMeta: {
      "doble-matrimonial": "Ideal para parejas · baño privado · WiFi · TV",
      "doble-twin": "Dos camas · baño privado · WiFi · TV",
      triple: "Hasta 3 personas · baño privado · WiFi · TV",
      "doble-mas-individual": "Cama doble e individual · baño privado · WiFi · TV",
      familiar: "Hasta 4 personas · espacio amplio · baño privado · WiFi · TV",
      individual: "Perfecta para una persona · baño privado · WiFi · TV",
    },
  },
  en: {
    metaTitle: "Book | Hostal Costabella",
    navBook: "Book",
    stepSearch: "Search",
    stepRooms: "Rooms",
    stepDetails: "Details",
    stepPayment: "Payment",
    langEs: "ES",
    langEn: "EN",
    searchTitle: "Find your stay",
    searchSubtitle: "Choose your dates and number of guests. Best rate on our official website.",
    checkin: "Check-in",
    checkout: "Check-out",
    adults: "Adults",
    children: "Children",
    searchCta: "See available rooms",
    roomsTitle: "Available rooms",
    roomsSubtitle: "Pick the option that best fits your trip.",
    nights: "nights",
    night: "night",
    perNight: "per night",
    totalStay: "Stay total",
    taxesNote: "Taxes included. Cancellation policy depends on rate.",
    selectRoom: "Select",
    modifySearch: "Change search",
    guestsSummary: "Guests",
    adultsWord: "adults",
    adultWord: "adult",
    childrenWord: "children",
    childWord: "child",
    roomWord: "room",
    roomsWord: "rooms",
    availabilityOk: "Available",
    availabilityFew: "Limited availability",
    back: "Back",
    backHome: "Home",
    detailsTitle: "Reservation details",
    detailsSubtitle: "Enter the lead guest information.",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    country: "Country / region",
    specialRequests: "Special requests (optional)",
    specialPlaceholder: "Approximate arrival time, room preferences…",
    continuePayment: "Continue to payment",
    paymentTitle: "Secure payment",
    paymentSubtitle: "Enter your card details to complete your booking.",
    summaryRoom: "Room",
    summaryGuest: "Guest",
    summaryStay: "Stay",
    summaryTotal: "Amount due",
    cardNumber: "Card number",
    cardExpiry: "Expiry",
    cardCvc: "CVC",
    payMethodCard: "Credit or debit card",
    payMethodBizum: "Bizum",
    payMethodTransfer: "Bank transfer",
    payCta: "Pay and confirm booking",
    payProcessing: "Processing payment…",
    confirmTitle: "Booking confirmed",
    confirmSubtitle:
      "Thank you. Your booking is registered and we have sent you an email with all the details.",
    confirmLocator: "Booking reference",
    confirmEmailNote: "Check your inbox and spam folder.",
    homeCta: "Back to home",
    errorDates: "Invalid dates. Check-out must be after check-in.",
    errorGuests: "Please enter at least one guest.",
    errorRoom: "No rooms match the number of guests. Adjust your search.",
    errorMissingRoom: "Select a room to continue.",
    roomNames: {
      "doble-matrimonial": "Double room (double bed)",
      "doble-twin": "Double room (twin beds)",
      triple: "Triple room",
      "doble-mas-individual": "Double + single bed room",
      familiar: "Family room",
      individual: "Single room",
    },
    roomMeta: {
      "doble-matrimonial": "Ideal for couples · private bathroom · WiFi · TV",
      "doble-twin": "Twin beds · private bathroom · WiFi · TV",
      triple: "Up to 3 guests · private bathroom · WiFi · TV",
      "doble-mas-individual": "Double and single bed · private bathroom · WiFi · TV",
      familiar: "Up to 4 guests · spacious · private bathroom · WiFi · TV",
      individual: "Solo travellers · private bathroom · WiFi · TV",
    },
  },
} as const;

export type BookingCopy = (typeof STRINGS)[BookingLocale];

export function bookingCopy(locale: BookingLocale): BookingCopy {
  return STRINGS[locale];
}

export function roomName(locale: BookingLocale, id: string): string {
  const names = STRINGS[locale].roomNames as Record<string, string>;
  return names[id] ?? id;
}

export function roomMeta(locale: BookingLocale, id: string): string {
  const meta = STRINGS[locale].roomMeta as Record<string, string>;
  return meta[id] ?? "";
}
